# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:09:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel, conint


class AftermarketListingAction(BaseModel):
    listingActionId: int = Field(..., description='Action Id')


class AftermarketListingExpiryCreate(BaseModel):
    domain: str = Field(..., description='Domain name')
    expiresAt: str = Field(..., description='Date when the domain expires')
    losingRegistrarId: conint(ge=1) = Field(
        ..., description='Losing registrar id for the domain'
    )
    pageViewsMonthly: Optional[int] = Field(
        None, description='Monthly traffic page view for the domain'
    )
    revenueMonthly: Optional[int] = Field(
        None, description='Monthly parking revenue (in USD micro unit) for the domain'
    )


class ErrorField(BaseModel):
    code: str = Field(
        ...,
        description='Short identifier for the error, suitable for indicating the specific error within client code',
    )
    message: Optional[str] = Field(
        None,
        description='Human-readable, English description of the problem with the contents of the field',
    )
    path: str = Field(
        ...,
        description="<ul>\n<li style='margin-left: 12px;'>JSONPath referring to a field containing an error</li>\n<strong style='margin-left: 12px;'>OR</strong>\n<li style='margin-left: 12px;'>JSONPath referring to a field that refers to an object containing an error, with more detail in `pathRelated`</li>\n</ul>",
    )
    pathRelated: Optional[str] = Field(
        None,
        description='JSONPath referring to a field containing an error, which is referenced by `path`',
    )


class ErrorLimit(BaseModel):
    code: str = Field(
        ...,
        description='Short identifier for the error, suitable for indicating the specific error within client code',
    )
    fields: Optional[List[ErrorField]] = Field(
        None,
        description='List of the specific fields, and the errors found with their contents',
    )
    message: Optional[str] = Field(
        None, description='Human-readable, English description of the error'
    )
    retryAfterSec: int = Field(
        ..., description='Number of seconds to wait before attempting a similar request'
    )


class Expiry(BaseModel):
    id: Optional[float] = None


class Domains(RootModel[List[str]]):
    root: List[str]


class V1AftermarketListingsExpiryPostRequest(
    RootModel[List[AftermarketListingExpiryCreate]]
):
    root: List[AftermarketListingExpiryCreate]


class Error(BaseModel):
    code: str = Field(
        ...,
        description='Short identifier for the error, suitable for indicating the specific error within client code',
    )
    fields: Optional[List[ErrorField]] = Field(
        None,
        description='List of the specific fields, and the errors found with their contents',
    )
    message: Optional[str] = Field(
        None, description='Human-readable, English description of the error'
    )
